id: IE797EA90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:09:39+00:00'
last_modified: '2022-06-08T07:06:47.960450+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1108
  title: སྟོབས་བཞིའི་བཤགས་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EAD1:
      image_group_id: I1CZ1378
      title: ''
      total_pages: 14
      order: 1
      base_file: EAD1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
